### ISSUE TITLE
Mauvais style pour le texte des salons de bronzage

### ISSUE THREAD

**Issue by phiphou** [cquest/osmfr-cartocss#11]
Pour les salons de bronzage qui sont taggés à la fois en `shop=beauty` ET `leisure=tanning_salon`, le style de texte rendu est celui utilisé pour les leisure et non pas celui attendu, à savoir le même que celui des salons taggués avec uniquement `shop=beauty`.

![tile openstreetmap fr](https://cloud.githubusercontent.com/assets/364418/12794039/84117da0-cab3-11e5-81a5-3f541c30bbe2.png)
http://tile.openstreetmap.fr/?zoom=20&lat=48.76288&lon=2.66622&layers=B0000000FFFFFF

**Comment by cquest** [comment]
Corrigé depuis !
