### ISSUE TITLE
Icône "bizarre" pour les shop=copyshop

### ISSUE THREAD

**Issue by phiphou** [cquest/osmfr-cartocss#12]
L'icône pour les `shop=copyshop` est très foncée, ce qui nuit à mon sens à sa lisibilité, surtout en comparaison avec celle du rendu officiel : 
![map-compare---bbbike org](https://cloud.githubusercontent.com/assets/364418/12828897/6d217850-cb87-11e5-8f94-3951912ad633.png)
[](http://tile.openstreetmap.fr/?zoom=20&lat=48.76293&lon=2.66601&layers=B0000000FFFFFF)
Sans forcément reprendre celle du rendu officiel, une version avec les lettres sur les pages en transparent total rendrait probablement mieux.

**Comment by cquest** [comment]
PR welcome !

Le 4 février 2016 à 21:48, Phiphou <notifications@github.com> a écrit :

> L'icône pour les shop=copyshop est très foncée, ce qui nuit à mon sens à
> sa lisibilité, surtout en comparaison avec celle du rendu officiel :
> [image: map-compare---bbbike org]
> <https://cloud.githubusercontent.com/assets/364418/12828897/6d217850-cb87-11e5-8f94-3951912ad633.png>
>
> <http://tile.openstreetmap.fr/?zoom=20&lat=48.76293&lon=2.66601&layers=B0000000FFFFFF>
> Sans forcément reprendre celle du rendu officiel, une version avec les
> lettres sur les pages en transparent total rendrait probablement mieux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cquest/osmfr-cartocss/issues/12>.
>



-- 
Christian Quest - OpenStreetMap France

**Comment by cquest** [comment]
Modifiée !

**Comment by phiphou** [comment]
Merci ;)

**Comment by phiphou** [comment]
Merci ;)
