### ISSUE TITLE
Missing z7.tif

### ISSUE THREAD

**Issue by rory** [cquest/osmfr-cartocss#15]
_(Apologies for using English)_

The style depends on a [raster file `z7.tif`](https://github.com/cquest/osmfr-cartocss/blob/7c684071b06e150f57df05982c9efd5f9a55d561/project.mml#L78-95) which is not included in this project. Is it possible to include it, or include step to download the data with `get-shapefiles.sh`? I think this is similar to #7.

**Comment by cquest** [comment]
Here it is: http://osm13.openstreetmap.fr/~cquest/z7.tif

A bit outdated, It needs a refresh... will do one asap.
