### ISSUE TITLE
"Invalid input syntax for integer" error on zoom 0-9

### ISSUE THREAD

**Issue by rory** [cquest/osmfr-cartocss#17]
_(Apologies for using English)_

In order to work around #16, I have created a dummy `params` table like so:

```
CREATE TABLE params ( num integer, key text);
INSERT INTO params (num, key) VALUES (0, 'buffer'); INSERT INTO params (num, key) VALUES (0, 'x_bleed'); INSERT INTO params (num, key) VALUES (0, 'y_bleed');
```

However I get the following error when trying to use kosmtik (f155674) on zoom 0-9 on tiles where there is data:

```
[httpserver] /osmfr-cartocss/tile/7/60/47.png?t=1468225659080 500
[httpserver] /osmfr-cartocss/poll/ 200
Trace
    at ProjectServer.raise (/home/rory/osm-software/kosmtik/src/back/ProjectServer.js:239:13)
    at /home/rory/osm-software/kosmtik/src/back/ProjectServer.js:73:34
    at /home/rory/osm-software/kosmtik/src/back/MetatileBasedTile.js:44:45
    at Object.oncomplete (fs.js:107:15)
Postgis Plugin: ERROR:  invalid input syntax for integer: ""
in getAsyncResult
```

This results in a HTTP 500 error and means no tile is returned. There are no errors for z10+. There are no errors for z0-9 tiles where there is no data in the database (and it instead falls back to the land polygon shapefiles).

**Comment by cquest** [comment]
INTEGER type casting is now done through a dedicated to_int() function taking care of values that do not look like integers.
