### ISSUE TITLE
amélioration des golfs

### ISSUE THREAD

**Issue by Olyon** [cquest/osmfr-cartocss#20]
golf =driving_range n'est pas rendu. il pourait l'être en vert (quand c'est une surface).
golf=tee peut être une surface ou un node, losque c'est une surface, en plus du rendu du point, il faudrai la remplir avec un vert aussi.

**Comment by cquest** [comment]
Ajoutés... des exemples pour vérifier ?

**Comment by Olyon** [comment]
Par exemple :
http://tile.openstreetmap.fr/?q=golf%20national
http://tile.openstreetmap.fr/?q=golf%20de%20teoula
http://tile.openstreetmap.fr/?q=golf%20de%20rennes%20Saint-Jacques

**Comment by Olyon** [comment]
Impécable! c'est super comme ça
