### ISSUE TITLE
craft=tiler n'est pas rendu

### ISSUE THREAD

**Issue by windu2b** [cquest/osmfr-cartocss#21]
Les vendeurs/poseurs de carrelage (craft=tiler) ne sont pas rendus.
Exemple ici : http://www.openstreetmap.org/node/4385629229 (situé à l'adresse suivante : 7 rue de bellevue, Bénouville)

**Comment by cquest** [comment]
En fait ce sont tout les craft=* qui ne sont pas rendus... il faudrait des icônes pour cela ;)

**Comment by cquest** [comment]
craft=* est visible depuis fin 2017...
