### ISSUE TITLE
boundary between France and Germany partly missing

### ISSUE THREAD

**Issue by althio** [cquest/osmfr-cartocss#24]
< des allemands sont intéressés par ce problème, je reporte donc en anglais >

The boundary between France and Germany is broken near Luxembourg, in this French-style carto rendering (but not in other renderings).

http://tile.openstreetmap.fr/?zoom=10&lat=49.27053&lon=6.44678
[mapcompare mc.bbbike.org](http://mc.bbbike.org/mc/?lon=6.504917&lat=49.352349&zoom=10&num=4&mt0=osmfr&mt1=mapnik&mt2=osm-administrative-boundaries&mt3=osmfr-hot&marker=)
[![screenshot mapcompare](https://cloud.githubusercontent.com/assets/9863567/20097780/861bbc86-a5b0-11e6-8849-c705e29e7ee8.png)](http://mc.bbbike.org/mc/?lon=6.504917&lat=49.352349&zoom=10&num=4&mt0=osmfr&mt1=mapnik&mt2=osm-administrative-boundaries&mt3=osmfr-hot&marker=)

Also seen on uMap with the defaut FR-style, reported by @wambacher
https://github.com/umap-project/umap/issues/374
https://osm.wno-edv-service.de/images/osm/snaps_2016/umap_still_defect.png

**Comment by wambacher** [comment]
nobody cares :(

**Comment by cquest** [comment]
I care...

It comes from a database problem.
I've not been able to solve it yet.

As we're about to switch to a new tile server and backend database, this should be solved quite soon with the new fresh DB.

**Comment by wambacher** [comment]
Thanks.

Yyes i agree - there must be something wrong/missing in the local database. And it's not easy to solve that. One trick is to "tickle" all missing elements (ways and nodes of the unvisible boundary part) by moving them some centimeters to enforce a diff update. tell me if i should do that.

Regards
walter

**Comment by cquest** [comment]
We're (slowly) moving to a new server where the DB is fine... have a preview here: http://umap.openstreetmap.fr/fr/map/test-rendu-osmfr_99740#9/49.0217/7.0354

**Comment by cquest** [comment]
New server, DB and tiles are online and the boundary is now correctly rendered :)
