### ISSUE TITLE
[database] syntax error at or near "PARALLEL"

### ISSUE THREAD

**Issue by MaelREBOUX** [cquest/osmfr-cartocss#29]
Suite de #27 (https://github.com/cquest/osmfr-cartocss/commit/ef68e925ce63208f5b4226b8afa512f8927941a8), ajout de la fonction _to_int_ et _fr_abbrev_ impossible :

```sql
CREATE OR REPLACE FUNCTION to_int(text) RETURNS bigint
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $_$ select left(regexp_replace(coalesce('0'||$1,'0'),'^([0-9]*).*','\1'),12)::bigint; $_$;

ERROR:  syntax error at or near "PARALLEL"
LINE 2:     LANGUAGE sql IMMUTABLE PARALLEL SAFE
```

Ubuntu 16.04, postgreSQL 9.5 + PostGIS 2.2

**Comment by MaelREBOUX** [comment]
Bien entendu

```sql
CREATE OR REPLACE FUNCTION to_int(text) RETURNS bigint
    LANGUAGE sql IMMUTABLE
    AS $_$ select left(regexp_replace(coalesce('0'||$1,'0'),'^([0-9]*).*','\1'),12)::bigint; $_$;
```
est accepté.

**Comment by cquest** [comment]
J'utilise désormais postgres 9.6 (et postgis 2.3) et donc ses capacités de paralélisme... d'où cette précision ans la définition de la fonction.

**Comment by MaelREBOUX** [comment]
m'en étais douté ;)
mais ça mérite d'être documenté du coup. je te prépare une PR.
