### ISSUE TITLE
Postgis Plugin: ERROR:  Operation on mixed SRID geometries in getAsyncResult

### ISSUE THREAD

**Issue by MaelREBOUX** [cquest/osmfr-cartocss#30]
Le calcul des tuiles se fait bien entre les niveaux / zoom 0 à 10.
Mais impossible de rendre une tuile au niveau 11.
Renderd produit l'erreur suivante :

```
renderd[10707]: ERROR: failed to render TILE fr 11 1008-1015 712-719
renderd[10707]:    reason: Postgis Plugin: ERROR:  Operation on mixed SRID geometries in getAsyncResult
```

**Comment by MaelREBOUX** [comment]
Un problème / un manque lors de l'import des données ?

**Comment by MaelREBOUX** [comment]
Alors les tables planet_ … sont en projection 900913 et la table / couche contour n'a pas de projection définie.

**Comment by cquest** [comment]
Etonnant si la table contour est vide.

Pour info, osm2pgsql utilise désormais l'EPSG:3857 au lieu du 900913 officieux. J'ai tout migré dernièrement en 3857.

**Comment by MaelREBOUX** [comment]
3 questions du coup :
- comment / à quel moment on dit à osm2pgsql de travail en 3857 (pour moi 900913 est effectivement obsolète) ?
- tu confirmes que la table contour doit être vide
- faut-il indiquer à osm2pgsql d'utiliser le style  style.xml lors de l'import des données ?

**Comment by cquest** [comment]
Quelle version d'osm2pgsql utilises-tu ? La 0.90 ou 0.92 fonctionne en 3857 par défaut.

Pour "contour", je devrais carrément supprimer le layer (qui est en status=off)...

Pour le style.xml, j'ai utilisé celui par défaut.

**Comment by MaelREBOUX** [comment]
> Quelle version d'osm2pgsql utilises-tu ?

Suis au bureau : peux pas savoir là maintenant mais c'est celle qui vient des dépôts officiels via ```apt-get install osm2pgsql```. Amha c'est 0.90 mais je confirme ce soir.

> Pour le style.xml, j'ai utilisé celui par défaut

Soit sans le préciser dans la commande d'import. Idem.

**Comment by MaelREBOUX** [comment]
$ osm2pgsql
osm2pgsql SVN version 0.88.1 (64bit id space)

il y a une option   -E|--proj num    Use projection EPSG:num

Ca sent l'install par npm ça ?

**Comment by cquest** [comment]
Je compile directement osm2pgsql, c'est du C/C++.

**Comment by MaelREBOUX** [comment]
je viens de lancer dans la version 0.90

osm2pgsql -d osm --hstore --slim --cache 2200 -E 3857 bretagne-latest.osm.pbf

on va voir ce que ça donne…

**Comment by MaelREBOUX** [comment]
avec l'option  -E 3857  les tables palnet_ sont bien en EPSG:3857 (pseudo mercator).
Maintenant voir si renderd se comporte mieux.

**Comment by MaelREBOUX** [comment]
Alors ça se passe très bien jusqu'au niveau 13 pour le moment donc je vois pas pourquoi ça n'irait pas sur les niveaux >

En revanche, j'ai beaucoup de  ```rendering failed with command 4, pausing. ``` et je ne sais pas si je dois y prêter attention ou pas.

```
render_list -a -m fr -s /var/run/renderd/renderd.sock -n 3 -t /data/osm/tiles/ -z 13 -Z 13 -x 3978 -y 2817 -X 4066 -Y 2870
debug: init_storage_backend: initialising file storage backend at: /data/osm/tiles/
Rendering client
Starting 3 rendering threads
Rendering all tiles from zoom 13 to zoom 13
Rendering all tiles for zoom 13 from (3978, 2817) to (4066, 2870)
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
rendering failed with command 4, pausing.
Waiting for rendering threads to finish
rendering failed with command 4, pausing.

*****************************************************
*****************************************************
Total for all tiles rendered
Meta tiles rendered: Rendered 84 tiles in 142.74 seconds (0.59 tiles/s)
Total tiles rendered: Rendered 5376 tiles in 142.74 seconds (37.66 tiles/s)
Total tiles handled: Rendered 84 tiles in 142.74 seconds (0.59 tiles/s)
*****************************************************
Zoom 13: min:  1.0    avg:  3.8     max: 14.5     over a total of    267.7s in 70 requests
*****************************************************
*****************************************************
```

**Comment by cquest** [comment]
max_async_connection est beaucoup plus facile à modifier dans le projet YAML, il n'apparait qu'une fois au début (factorisation).

**Comment by MaelREBOUX** [comment]
c'est noté.
