### ISSUE TITLE
osmfr V2017 problème OL3

### ISSUE THREAD

**Issue by Rocca2017** [cquest/osmfr-cartocss#34]
Bonjour à tous et à toutes.

Je me permets de poster le présent message, car j'ai un petit souci depuis la mise à jour du fond de carte OSM-Fr en V2017.

En effet, la carte ne fonctionne plus depuis, je pense, cette mise à jour.

J'utilise OL3 dans le cadre d'une cartographie perso développée pour mon travail.

J'ai regardé le code javascript, de l'exemple, pour appeler le fond de carte. A priori rien n'a bougé avec la mise à jour (j'ai le même code).

Pourtant, la carte ne s'affiche plus contrairement à osm standard, hot et road.

Le serveur ne renvoie pas d'erreur d'après ce que j'ai pu comprendre (je débute).

En fait, c'est comme si la connexion était très, très lente. La suite du code javascript s'exécute sans souci, les couches kml et json s'affichent mais le fond de carte non en ce qui concerne uniquement osm-fr.

Ce qui est dommage, le but étant également de faire découvrir et utiliser ce super boulot. J'en profite pour saluer ce boulot d'ailleurs.

Merci d'avance pour toutes suggestions ou solutions..

**Comment by cquest** [comment]
Bonjour,

Quelle URL utilisez-vous pour accéder aux tuiles ?
Peut-on voir cette carte OL3 quelque part pour comprendre ?

**Comment by Rocca2017** [comment]
Pour la carte, je ne peux y donner accès car c'est en local (sur le serveur) avec des données confidentielles.

Néanmoins, je peux sans problème poster le code ou une image si c'est possible ou un code sans les données.

Url avec le code :

Carte 3 = new ol.layer.Tile({
Source : New ol.source.OSM({
Url : 'http://{a-c}.tile.openstreetmap.fr/osmfr/{z}/{x}/{z}.png'
})
});

En vous remerciant. 😀 

(désolé pour certaines majuscules, je suis sur un téléphone).

**Comment by cquest** [comment]
Le debug du navigateur indique quoi sur les requêtes pour obtenir les images ?
Il n'y a pas un problème http/https ?

**Comment by Rocca2017** [comment]
Le débogueur n'indique rien. Pour lui le code s'exécute normalement. 

Histoire d'être un  peu plus précis. 

Lorsque je lance (lien html) la cartographie, je charge une des cartes (par défaut OSM Standard). Sur cette carte apparait 3 points (couche GeoJson) en même temps que le fond bleu (défini dans le css) puis les tuiles fond leur apparition peu à peu (en fonction du débit).


Ensuite, via des boutons, je rajoute des marqueurs en fonction de la demande (voilà pour le fonctionnement en temps normal). 

OSM-Fr jusqu'à il y a quelques temps fonctionnait de la même façon sans problème (l'affichage des différentes tuiles était un peu plus lent, comme pour la carte "hot"). 

A l'heure actuelle, j'ai le fond bleu qui apparait ainsi que mes 3 points (geoJson), l'échelle, le bouton E, le layer switcher.... Si je manipule les boutons, les marqueurs apparaissent également à l'écran mais sur un fond bleu.

C'est pour cela que j'indique que cela se passe comme si la connexion était très très très lente. Le code javascript s'exécute comme avant (je n'ai rien changé depuis) sauf que les tuiles n'apparaissent pas. 

Le fond reste donc bleu.

J'ai jeté également un oeil au temps de réponse du serveur, lors du chargement de la page.

La carte OSM-Fr se comporte comme les autres. Les tuiles (.png) se chargent en quelques ms.

Cela va de 39 ms à 117 ms (rien d'anormal, avec le carte "hot" j'ai des temps bien plus élevé et elle s'affiche de 150 ms à 2200 ms) avec un code état 200 : OK (dans ongle réseau / image).

C'est pour ça que je trouve le problème quelque peu surprenant. Tout se passe comme si tout vas bien, à part que mon fond reste bleu à la place de faire apparaitre les tuiles. 

EDIT : que voulez-vous dire par http/https ? Les cadenas apparaissent barrés comme pour toutes les autres OSM.

**Comment by cquest** [comment]
Si vous êtes en HTTPS, il faudrait appeler les tuiles en HTTPS aussi pour éviter que les règles de sécurité du navigateur puisse bloquer l'accès aux tuiles (et avoir un cadenas normal).

Dans le débuggueur les tuiles sont vides ? Quelle taille pour les fichiers (Ko) ?

**Comment by Rocca2017** [comment]
Ah d'accord, je n'avais pas compris votre question. J'en prends note (débutant).

Je viens de lancer la cartographie de chez moi, où j'ai plus d'outils adéquats, et il se trouve que j'obtiens les résultats suivants dans l'onglet réseau puis analyse "image". 

Dans le cas de la carte OSM Standard qui fonctionne sans souci j'obtiens :
- un petit triangle orange avec code d'état 304 devant GET qui signifie "not modified" et un cadenas vert.

A noter que j'ai le même résultat avec l'affichage d'une carte BING Map rendu "road". 


Pour OSM-Fr : 
- un petit point vers avec code d'état 200 devant GET qui signifie "OK" et un cadenas vert.

Et surtout pas d'affichage des tuiles.

Pour la carte Hot : 
- un petit triangle orange  avec code d'état 304 et des codes d'état 200 ainsi qu'un cadenas gris barré rouge.

La carte s'affiche sans problème. 

Pour la carte OSM road : 
- un petit point vers avec code d'état 200 devant GET qui signifie "OK" et un cadenas cadenas gris barré rouge.

La carte s'affiche sans problème. 


En ce qui concerne la quantité de données, j'obtiens dans tous les cas, en ce qui concerne les images, zéro kilo-octet.

J'ai tenté la modification en mettant des https mais sans résultat : 

carte3 = new ol.layer.Tile(
    		{
		title: 'Carte OSM-Fr',
		type: 'base',
		source: new ol.source.OSM({ 
    		url: 'http**## s**://{a-c}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png' 
   		}) 
		}); 

Enfin, la seule différence que j'ai pu voir (peut-être d'autres) est que sur la carte OSM-Fr, onglet "en-têtes" (une fois cliqué sur une image) je n'ai aucune ligne affichant "Acess-Control-Allow-Origin" : "*".

**Comment by Rocca2017** [comment]
Bonjour,

Petit détail en regardant de plus près dans les données du navigateur mozilla.

Dans l'onglet réseau puis onglet réponse, dans le cas de umap ou votre exemple de carte, j'ai la description et une image représentant la tuile en question.

Dans mon cas, toujours pour la carte osm-fr, j'ai les informations également (nom image, dimensions, type mime, encodage).
Par contre, la tuile en question ne s'affiche pas.

Si je sélectionne l'url de la requête et que je la colle dans une page du navigateur, l'image ou plutôt la tuile en question apparait bien.

On dirait que le problème ne vient que de l'affichage de la tuile. Tout fonctionne sauf cet affichage des tuiles.

Je m'explique :
-les tuiles sont bien là, elles sont chargées dans le navigateur,
-j'ai les informations concernant les tuiles...

Du coup, l'accès pour test à l'ancienne (2016) carte est-il possible ?

Voulez-vous que j'établisse une version allégée mais avec le même souci de ma cartographie ? Il suffira de poster le lien pointant vers un espace de stockage permettant le téléchargement de cette version allégée (cela demande une certaine confiance de votre part).

**Comment by cquest** [comment]
C'est sûrement l'absence du "Acess-Control-Allow-Origin" : "*" qui pose problème.
Il a été ajouté ce qui devrait régler le problème.

**Comment by Rocca2017** [comment]
Très bien. 
Du coup, ce sera opérationnel à partir de quand (environ) ? Afin de pouvoir indiquer si la solution est ou non trouvée. 
Merci en tout cas pour votre aide.

**Comment by cquest** [comment]
C'est déjà en place.

**Comment by Rocca2017** [comment]
Dans ce cas, cela n'a pas réglé mon souci :( 

Je viens de tester à l'instant et ça reste identique à ce qui est écrit ci-dessus. Pas d'affichage des tuiles.

La mention "Acess-Control-Allow-Origin" : "*" n'apparait toujours pas (adresse IP du serveur : 100.78.56.201:8080), code d'état 200 : OK

**Comment by cquest** [comment]
C'est sûrement dû au cache... cei va se régler au fur et à mesure de sa mise à jour.

**Comment by Rocca2017** [comment]
Bonsoir, vous avez raison.
Je viens d'arriver chez moi et la carte remarche.
La mention "Acess-Control-Allow-Origin" : "*" apparait maintenant (get 304).

Certaines tuiles sont en double (le cache comme vous l'indiquez).

Beau travail en vous remerciant une nouvelle fois.
🙂🙂
