### ISSUE TITLE
Page Apache par défaut quand on accède à tile.openstreetmap.fr

### ISSUE THREAD

**Issue by neitsab** [cquest/osmfr-cartocss#41]
Bonjour,

En essayant d'accéder au serveur [tile.openstreetmap.fr](http://tile.openstreetmap.fr) pour voir le rendu OSM-FR, je tombe sur la page Apache par défaut d'Ubuntu.

C'est la même chose que ce soit avec le sous-domaine ou un requête spécifique ([exemple](http://tile.openstreetmap.fr/?zoom=13&lat=48.3735&lon=2.95276&layers=B0000000FFFFTF)), depuis un PC ou un téléphone, depuis des connexions différentes... J'ai essayé la plupart des liens de [FR:Servers/tile.openstreetmap.fr](https://wiki.openstreetmap.org/wiki/FR:Servers/tile.openstreetmap.fr), qui renvoient tous vers cette page par défaut.

C'était déjà comme ça il y a deux semaines environ. J'ai cherché une annonce signalant que le serveur était en maintenance, mais n'ayant rien trouvé j'ai préféré ouvrir ce rapport afin de clarifier les choses.

Merci pour tout le travail effectué sur OSM !

**Comment by Niarolf** [comment]
Bonjour neitsab,
avec cette adresse de test je l'ai très bien : http://a.tile.openstreetmap.fr/osmfr/0/0/0.png
dans l'exemple d'url que tu donnes, je remarque que tu n'as pas le a. , b. ou c. dans le nom de domaine et la query n'ets pas comme dans le wiki qui doit être de la forme z/x/y.png.

Bien à toi

**Comment by neitsab** [comment]
Bonjour Niarolf,

Merci pour ta réponse, en effet je n'ai pas essayé ce type d'adresses ne sachant pas par quelle valeur remplacer les variables. Donc les tuiles/images statiques sont toujours servies correctement, pas de problème.

Par contre, qu'en est-il du serveur de carte interactif anciennement disponible à l'adresse http://tile.openstreetmap.fr, et mis en avant:
- sur la page d'accueil du présent dépôt (première ligne à droite de la description)
- sur le [wiki](https://wiki.openstreetmap.org/wiki/FR:Serveurs/tile.openstreetmap.fr) susmentionné, dès la première ligne
- sur la page http://openstreetmap.fr/outils ?

Si la carte interactive a été désactivée et que tout est normal, pas de problème ! Dans ce cas je voudrais juste suggérer de mettre à jour les liens susmentionnés qui référencent http://tile.openstreetmap.fr de manière proéminente, parce qu'actuellement ça donne le sentiment d'un bug d'arriver sur cette page d'Apache par défaut :smile:

**Comment by cquest** [comment]
Je dois remettre la page par défaut en route. Ce n'était pas prioritaire par rapport au reste des services qui devaient être remis en route suite à la panne du serveur (SSD HS et remplacé).

**Comment by cquest** [comment]
Pour ce genre d'issue, nous avons un projet dédié, car ici il s'agit uniquement de la feuille de style elle même..

C'est ici: https://github.com/osm-fr/infrastructure/issues/11

**Comment by neitsab** [comment]
Autant pour moi, j'avais cherché le projet approprié mais sans succès.

Merci pour l'explication et la prise en compte, et bonne continuation !
