### ISSUE TITLE
pg fonction to_int()

### ISSUE THREAD

**Issue by Niarolf** [cquest/osmfr-cartocss#42]
Bonjour,
postgresql fait une erreur pour la fonction to_int() qui est présente dans certaines requêtes dans le fichier project.mml transformé ensuite en xml.
Est-ce qu'une fonction particulière a été créée pour ces requêtes ?
Niarolf

**Comment by cquest** [comment]
Les fonctions ajoutées sont disponibles dans https://github.com/cquest/osmfr-cartocss/blob/master/functions.sql

**Comment by Niarolf** [comment]
Merci,
j'aurai du ouvrir les yeux !!!
