### ISSUE TITLE
Golfe du Morbihan : le nom de certaines île n'apparaît pas

### ISSUE THREAD

**Issue by adrien-github** [cquest/osmfr-cartocss#44]
Bonjour,
Dans le Golfe du Morbihan, le nom de certaines îles apparait bien sur la carte (par ex. Tascon), mais d'autre non ([île Bailleron](https://www.openstreetmap.org/way/500298936#map=15/47.5770/-2.7418), juste à l'ouest de Tascon)

http://tile.openstreetmap.fr/?zoom=14&lat=47.58322&lon=-2.76089&layers=B000000FFFFFF

Le nom des îles apparaît bien sur le rendu OSM officiel.

Bonne journée

**Comment by adrien-github** [comment]
Bonjour,

Toujours dans le golfe, le nom des récifs apparaît bien, mais pas leur contour. par exemple le [Grégan](https://www.openstreetmap.org/way/23031957) : 

http://tile.openstreetmap.fr/?zoom=16&lat=47.56589&lon=-2.91725&layers=B000000FFFFFF

Serait-il possible de les faire apparaître, comme sur le rendu OSM officiel ?

Bonne journée

**Comment by MaelREBOUX** [comment]
C'est parce que par rapport au style org, il manque une règle de style pour le tag "natural:reef" dans https://github.com/cquest/osmfr-cartocss/blob/master/landcover.mss

cf  https://github.com/gravitystorm/openstreetmap-carto/blob/311cae6e92f4ae8172dd302ee3d7edbbb4a99943/landcover.mss#L680-L683

+ tag à rajouter dans la requête aux données ici :  https://github.com/cquest/osmfr-cartocss/blob/master/osmfr.yml#L96
