### ISSUE TITLE
Bâti

### ISSUE THREAD

**Issue by ades222** [cquest/osmfr-cartocss#46]
Je ne sais pas si c'est vraiment un nouveau blèm. ou si je suis le seul…
En général rendu plutôt bien, me souvient plus les détails qui m'ont géné, mais c'est du détail. 
Par contre je persiste à trouver fort dommage que les immeubles ne soient pas rendus, même si c'est parfois pas très précis (encore que) la matérialisation de la différence entre deux immeubles me semble importante. 
La matérialisation des limites d'immeuble indique une différence du nombre de niveaux, une différence de travail de l'élévation en façade, une trace historique (ancien remparts…), enfin plein de chose qui permettent de lire une carte et de comprendre, ne serait-ce qu'où l'on est…
Une seconde chose tient au rendu des gare et des bureaux de poste, le rendu indique le nom de la commune (avec l'icône qui va ;-)), c'est un peu redondant lorsque le nom de la gare ou du bureau de poste (refs officielles) est le même que celui de la commune. Pas myen de faire un truc diu genre si nom bureau = nom commune alors rien sinon nom du bureau ?
voilà

**Comment by cquest** [comment]
**Bâti**: le rendu est déjà saturé d'information et très dense, c'est un choix pour la lisibilité qui a été fait, pour privilégier les informations "fortes", saisies par les contributeurs, plutôt que celles provenant majoritairement des données imparfaites du cadastre.

**Nom des POI**: Ce type de post-traitement est possible, mais lourd. Il ne ferait que compenser une mauvaise pratique courante sur name=* où l'on retrouve une valeur qui n'est pas un nom mais une forme de description. Discussions souvent menée sur talk-fr sans consensus clair final.
J'ajouterai aussi les mairies ou les cimetières dans la liste des POI mal nommés ;)

PS: Un sujet, une issue ;)
