### ISSUE TITLE
Arbres remarquables: natural=tree + denotation=natural_monument

### ISSUE THREAD

**Issue by cquest** [cquest/osmfr-cartocss#48]
Un rendu pour les différencier ?

**Comment by jragusa** [comment]
A noter que ces arbres remarquables possèdent aussi un nom qui est affiché contrairement à un arbre lambda qui en est généralement dépourvu

**Comment by Clairouin** [comment]
Bonjour,
Non, les arbres dits "remarquables" ne possèdent pas forcément un nom. Je parle d'arbres recensés, par exemple, par l'association A.R.B.R.E.S ( https://www.arbres.org/ ) ou par des associations ou collectivités locales. J'ai moi-même participé à un inventaire des arbres remarquables dans le département des Deux-Sèvres et je contribue actuellement à une même démarche sur Angers. 
Il serait intéressant d'avoir un rendu spécifique pour ces arbres (exceptionnels par leurs dimensions, leur âge, leur rareté, leur histoire, etc.) pour les distinguer des arbres "banals" cartographiés à juste titre, particulièrement en zone urbaine.
