### ISSUE TITLE
Établissements scolaires : nom en double

### ISSUE THREAD

**Issue by deuzeffe** [cquest/osmfr-cartocss#49]
Hello,

Soit https://tile.openstreetmap.fr/?zoom=19&lat=45.79398&lon=1.13195&layers=B00000000FFFFFF ou https://tile.openstreetmap.fr/?zoom=19&lat=45.79756&lon=1.13568&layers=B00000000FFFFFF le nom de l'établissement (primaire ou collège) est en double, comme si la couche osmfr rajoutait le sien sans enlever celui du cartocss standard.

Alors que là (maternelle) https://tile.openstreetmap.fr/?zoom=19&lat=45.79814&lon=1.1347&layers=B00000000FFFFFF le nom n'est pas répété.

J'ai loupé une subtilité dans les tag ou bien ?

Merci pour la réponse.

**Comment by cquest** [comment]
C'est un bug du rendu, pas de problème sur les tags.
Il y a quelques "area" comme ça où parfois on a un double nom qui est rendu... il va falloir que je reparte à la chasse ;)
