### ISSUE TITLE
How to use this stylesheet with renderd

### ISSUE THREAD

**Issue by Valachio** [cquest/osmfr-cartocss#50]
Hi.  Sorry if this is a noob question.

I followed the instructions in README.  But there is no .xml file, neither is there a .mml file for me to convert over to .xml with carto.

What am I supposed to do to get the .xml file for me to point to in `renderd.conf`?

**Comment by cquest** [comment]
The final .xml final is generated by cartocss, using the .yml and .mss files

I'm using Kosmtik to do this (and test the style).

**Comment by Baraganne** [comment]
> The final .xml final is generated by cartocss, using the .yml and .mss files
> 
> I'm using Kosmtik to do this (and test the style).

Hi,

Can you please detail how you generate the xml using cartocss and .yml + mss files?

PS : I'm french, just replying in English to continue this topic.

Thank you.

**Comment by MaelREBOUX** [comment]
See the OSM wiki :  https://wiki.openstreetmap.org/wiki/CartoCSS#Converting_to_Mapnik_XML

If you have a custom install of the carto sofware 

`./bin/carto ./files/<your project>/<your project>.mml > mapnik.xml`

A custom tile server with renderd+Mapnik uses these .xml project files.

**Comment by franceska470** [comment]
Hi Baraganne,
Have you found how to generate the xml file for osmfr -cartocss ?
I have the same problem, I don't know how to do it...
Thank you !

**Comment by UNI49** [comment]
Hi @cquest 

Same issue here, the original project [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto) has a project.mml, this one haven't. How to convert this project to a usable project.mml ?

Howdo you do with just .yml and .mss ?

Thanks for help.

**Comment by MaelREBOUX** [comment]
We (this french style and the breton style) switched to YAML because it is more less verbose than MML. And finaly it is easier to maintain the project.

Look at this script to transform YAML to XML readable by renderd :  https://github.com/osm-bzh/osmbr-mapstyle/blob/master/scripts/yaml2xml.sh

Tip :
```
cp osm_br.yml osm_br.mml
carto osm_br.mml > osm_br.xml
```

**Comment by UNI49** [comment]
Thanks for your help @MaelREBOUX it's simple, but not really explain in carto or here, that's why it's confusing.

**Comment by MaelREBOUX** [comment]
For help on styling with the Carto technlogy (map project file -mml- + stylesheets -mss-), please read :
* https://cartocss.readthedocs.io/en/latest/index.html
* https://carto.com/developers/styling/cartocss/
* https://cartocss.readthedocs.io/en/latest/mml.html#mml-file-structure
