### ISSUE TITLE
Erreur de génération du rendu

### ISSUE THREAD

**Issue by Baraganne** [cquest/osmfr-cartocss#55]
J'ai réussi à régler mon problème précédent (erreur d'import), mais je me retrouve maintenant avec l'erreur suivante au moment de la génération du rendu:

Trace
at ProjectServer.raise (/root/src/kosmtik/src/back/ProjectServer.js:267:13)
at /root/src/kosmtik/src/back/ProjectServer.js:81:30
at /root/src/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
at loaded (/root/src/kosmtik/node_modules/mapnik-pool/index.js:23:37)
Postgis Plugin: ERREUR: plus d'une ligne renvoyée par une sous-requête utilisée comme une expression
CONTEXT: fonction SQL « bbbox », instruction 1
in executeQuery Full sql was: 'SELECT * FROM /* water-lines */ (select st_intersection(bbbox(ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 3857),0,0,0),way) as way,waterway,disused,lock,coalesce(tags->'name:fr',tags->'int_name',name) as name, case when coalesce(tunnel,covered) in ('yes','true','1') then 'yes'::text else coalesce(tunnel,covered) end as tunnel, tags->'CEMT' as cemt, case when tags->'CEMT'~'V' then 'true' else '' end as cemt_large, case when tags->'motorboat'='yes' then 'motorboat' when tags->'boat'='yes' then 'boat' else 'no' end as boat from planet_osm_line where way && ST_SetSRID('BOX3D(-3.402823466385289e+38 -3.402823466385289e+38,3.402823466385289e+38 3.402823466385289e+38)'::box3d, 3857) AND osm_id>0 AND waterway in ('weir','river','canal','derelict_canal','stream','drain','ditch','wadi') and (bridge is null or bridge not in ('yes','true','1','aqueduct')) order by z_order ) as water_lines LIMIT 0'
encountered during parsing of layer 'water-lines' in Layer

Pour le coup j'avoue être un peu dépassé par cette erreur.

Merci d'avance

**Comment by cquest** [comment]
Réponse très en retard, désolé...

Cette fonction "bbbox" se trouve dans functions.sql avec quelques autres petites choses utiles utilisées par les requêtes SQL de ce style.
