### ISSUE TITLE
Country-level border issues

### ISSUE THREAD

**Issue by kocio-pl** [cquest/osmfr-cartocss#6]
There are 2 problems with country-level borders probably, both visible here:

http://tile.openstreetmap.fr/?zoom=9&lat=50.0866&lon=23.40664&layers=B0000000FFFFFFF

1. From z>=9 Ukraine is covered with water.

2. In some countries parts of the country border are invisible up to z<=10, and after z>=11 are visible, but lighter than the rest. Probably it's about name=* tags (when there's no such tag, the border is invisible/lighter)?

Are these problems caused by bad tagging or is it a bug in this rendering style?

**Comment by cquest** [comment]
This was caused by faulty data in the database
