### ISSUE TITLE
Coupure de texte en limite de tuiles

### ISSUE THREAD

**Issue by frodrigo** [cquest/osmfr-cartocss#66]
Repport de https://github.com/osm-fr/infrastructure/issues/50

**Comment by cquest** [comment]
J'ai généralisé l'usage des directives "avoid-edges" dans le cartocss, qui est maintenant bien bien mieux géré par mapnik que lorsque la feuille de style a été originellement mise au point. Ces petits défauts doivent avoir disparu.
