### ISSUE TITLE
installation manque des fichiers

### ISSUE THREAD

**Issue by monsieur-a** [cquest/osmfr-cartocss#7]
Les fichiers shape et raster nécessaire au rendu ne sont pas indiqué dans le readme, il n'y a que les références au rendu international.
Le style osm2pgsql semble ne pas être le style standard, notament pour les couches non actives :  vélo ...

**Comment by Cyrille37** [comment]
Aussi quand on ouvre le projet dans TileMill il y a des fichiers de données avec un chemin en dur :

ENOENT, readdir '/data/work/mapnik/data/land-polygons-split-3857'

**Comment by kocio-pl** [comment]
My French is very basic, but I guess it's about installation problems. I did a workaround by making hard directories and linking to downloaded data, but was still unable to locate file z7.tif:

https://github.com/cquest/osmfr-cartocss/blob/master/project.mml#L88
