### ISSUE TITLE
Les forêts sont rendues très différemment entre zoom 7 et 8

### ISSUE THREAD

**Issue by zorun** [cquest/osmfr-cartocss#71]
Il y a une grosse différence de rendu des forêts entre le zoom 7 et le zoom 8.

C'est particulièrement visible en Suède, où de larges zones de forêt n'apparaissent qu'à partir du zoom 8. Essayer de zoomer un coup vers le centre de la carte suivante, les forêts apparaissent : http://tile.openstreetmap.fr/?zoom=7&lat=60.35414&lon=13.62&layers=B00000000FFFF

La même zone sur le rendu standard OSMF a bien les forêts manquantes, même aux faibles zoom : https://www.openstreetmap.org/#map=7/60.35414/13.62

Il s'agit d'un ensemble de multipolygones `landuse=forest`, je ne vois rien de particulier qui pourrait empêcher leur rendu : https://overpass-turbo.eu/s/X79

Peut-être que ces multipolygones sont trop petits ?

**Comment by zorun** [comment]
Inversement, à l'ouest de la Pologne (Lubusz, entre Poznan et Berlin), certaines forêts **disparaissent** quand on zoome du 7 au 8 : 

- zoom 7 : on voit des forêts assez denses http://tile.openstreetmap.fr/?zoom=7&lat=52.12507&lon=15.63947&layers=B00000000FFFF
- zoom 8 : quasiment plus rien http://tile.openstreetmap.fr/?zoom=8&lat=52.15935&lon=15.60444&layers=B00000000FFFF
- zoom 9 : on voit des petits morceaux de forêt réapparaître http://tile.openstreetmap.fr/?zoom=9&lat=52.09021&lon=15.40394&layers=B00000000FFFF
- zoom 10 : les forêts reviennent http://tile.openstreetmap.fr/?zoom=10&lat=52.09696&lon=15.21855&layers=B00000000FFFF

Ça a l'air très lié aux politiques locales de découpage des gros multipolygones...

**Comment by cquest** [comment]
Le problème est effectivement lié au découpage en toute petites surfaces. Pour accélérer le rendu, seules les polygones d'une taille suffisamment visible sont sélectionnées... j'ai déplacé la limite pour éviter cet effet.
