### ISSUE TITLE
Point pour healthcare sans icône

### ISSUE THREAD

**Issue by deuzeffe** [cquest/osmfr-cartocss#72]
Hello,

Merci pour 0b743c9.

Est-il possible d'avoir un point rouge pour tous les healthcare sans icône dédiée ?

Merci pour la réponse, quelle qu'elle soit.

**Comment by cquest** [comment]
Exemple: https://osm.cquest.org/dev/#19/48.82889/2.36903

**Comment by deuzeffe** [comment]
Impec ! Thx.
Reste plus qu'à le faire avaler au rendu standard :P

**Comment by deuzeffe** [comment]
Je suis devenue daltonienne ou les POI santé sont passés du rouge au bleu ?
