### ISSUE TITLE
Camping : nom en double

### ISSUE THREAD

**Issue by deuzeffe** [cquest/osmfr-cartocss#73]
Ici : https://layers.openstreetmap.fr/?q=Aixe-sur-Vienne&zoom=19&lat=45.79826&lon=1.13958&layers=B000000000FFFFFFFFFFFFFFFFFFFFFFFFF

HTH

**Comment by cquest** [comment]
Un lien sur https://umap.openstreetmap.fr/fr/map/rendu-fr-en-developpement_483858 est préférable... c'est la dernière version de travail de la feuille de style car le lien au dessus ne montre aucun camping.

**Comment by deuzeffe** [comment]
Ooops, my bad. C'est ok sur la version de travail, ici : https://umap.openstreetmap.fr/fr/map/rendu-fr-en-developpement_483858#20/45.79832/1.13979

Désolée pour le dérangement.
