### ISSUE TITLE
Gares bureaux de poste nom superflu dans certain cas

### ISSUE THREAD

**Issue by ades222** [cquest/osmfr-cartocss#74]
L'import des gares et des bureau de poste fait que name est saisi, nom de la commune (ou de l'aglo dans le cas de communes nouvellement regroupées) en général, ok quand il y a plusieurs gares ou plusieurs bureaux dans une même aglomération le name=** apparait sur les rendus, ce qui est superfétatoire quand il n'y a qu'un seul bureau et qu'une seule gare dans la commune ( ou l'ancienne com).
Serait-il possible que le rendu, dans ce cas, n'indique que 'Gare' ou 'Gare SNCF' et "La Poste" ou "La Poste" ou "Bureau de poste" ou agence postale"  ou m^me rien si le logo de la poste apparait
Ça éviterai de voir le nom de la Com apparaitre de 3 à 4 fois sur le rendu.
En faisant la "promotion" d'OSM, j'ai eu 2 ou 3 fois des remarques sur ce point, allant jusqu'à la mise en caus de la qualité d'OSM…

**Comment by cquest** [comment]
Le problème se situe plutôt dans les données... name=* ne devrait pas être utilisé dans ces cas, car il ne s'agit pas d'un nom choisit, afin de différencier des objets.
