### ISSUE TITLE
building=train_station non rendu

### ISSUE THREAD

**Issue by Stefal** [cquest/osmfr-cartocss#86]
Soit ce type de batiment n'est pas rendu, soit certains landuse passent par dessus, car les quais ne sont pas rendu non plus.

Exemple à Louvres : 
https://www.openstreetmap.org/node/295984594#map=19/49.04944/2.50248

osm.org

![image](https://user-images.githubusercontent.com/8255984/138343286-84330fb2-09aa-45fe-a166-3012a7fcce3d.png)

osm-fr

![image](https://user-images.githubusercontent.com/8255984/138343445-62d1d601-f221-4699-9021-83e41dd56b6a.png)

**Comment by cquest** [comment]
Oui c'est corrigé

http://osm.cquest.org/dev/#19/49.04944/2.50248

mais pas encore déployé !
