### ISSUE TITLE
Frontières interrompues

### ISSUE THREAD

**Issue by tbertels** [cquest/osmfr-cartocss#87]
Certaines frontières sont interrompues, par exemple près du Logone Oriental : http://tile.openstreetmap.fr/?q=logone%20oriental

**Comment by cquest** [comment]
Il manque un admin_level=* sur les way qui sont utilisés pour le rendu des frontières.

**Comment by tbertels** [comment]
admin_level=* est bien présent sur la relation : https://www.openstreetmap.org/relation/2361304#map=5/15.602/18.737
Il y a le même problème pour différents pays, par exemple le sud-est de la Pologne : https://www.openstreetmap.org/way/434994452#map=14/49.1196/22.8307
